### ISSUE TITLE
Issue on docs

### ISSUE THREAD

**Issue by mrezabidhendi** [duneanalytics/dune-docs#132]
Path: /api-reference/executions/endpoint/execute-query

There's a missing quotation mark in the end of the second line of the sample cURL command on the right.
```
curl -X POST "https://api.dune.com/api/v1/query/{{query_id}}/execute"   \
  -H "X-Dune-API-Key: {{api_key}}                                       \
  -H "Content-Type: application/json"                                   \
  -d '{"query_parameters": {"param1":24}, "performance": "large"}'
```
When you fill the Query Parameters in that page it does not execute as intended. However it works fine in Postman! Therefore I think it is related to the curl command having the typo.

**Comment by agaperste** [comment]
@mrezabidhendi Thank you for flagging, should be fixed now!
