### ISSUE TITLE
Update on Credit docs

### ISSUE THREAD

**Issue by mara-dune** [duneanalytics/dune-docs#136]
Path: /learning/how-tos/credit-system-on-dune

Here is a drafted revision of the documentation page on credits for Dune, incorporating enhancements for clarity:

# Understanding Credits on Dune
### What are Credits?
Credits are the key to accessing a wide range of functions on the Dune platform. Whether you're delving into data queries or simply exploring dashboards, knowing how credits operate is crucial.
### Why are Credits Important for All Users?
All actions on Dune, from running complex data queries to simply refreshing your view to see the latest insights, consume credits. It's vital for every user, viewer, or creator alike, to be mindful of their credit usage.

###  🎟️ Monthly Credit Allowance
- **Set Number of Credits:** Each month, your subscription plan provides a set allotment of credits.
- **Top-Up:**  Run out of credits? Our 'Pay as I go' option lets you add more anytime, ensuring your work is always in flow.
### 🔄 Rollover Policy
- **Monthly Refresh:** Credits reset at the start of each billing cycle; they **_do not roll over to the next month_**.
- **Maximize Use:** Plan your activities to maximize the utility of your credits.
### 👥 Team Accounts
- **Collective Pool:** All team members draw from a shared pot of credits. Sync up to make the most of your resources.

## Understanding Credit Use on Dune
Credits power your work on Dune, and here's how they're typically used:
- [**Queries:**](https://docs.dune.com/web-app/query-editor/query-window) Running and creating queries consumes, varying based on complexity.
- [**Engine Power:**](https://docs.dune.com/query-engine/query-executions#query-engine-size) Larger tasks need more powerful engines, increasing credit usage, which we detail upfront.
- [ **Refreshes:**](https://docs.dune.com/web-app/dashboards#keeping-your-dashboard-up-to-date) Refreshing dashboards or widgets consumes credits; exact numbers are displayed contextually.
- [**Exports:**](https://docs.dune.com/learning/how-tos/export-data-out) Exporting data costs credits, with higher amounts for larger exports. Estimates are provided beforehand.
- [**Auto-Runs:**](https://docs.dune.com/web-app/query-editor/query-scheduler) Scheduling queries to run regularly consumes credits each time, with details available in the setup options.

### Estimating Credit Usage
Understanding how your activities on Dune consume credits can help you manage your resources more effectively:
- **Credit Estimates:** Always check for tooltips or on-screen indicators that provide real-time estimates of credit costs before you perform actions.
- **Simulation Tools**: Use preview features, where available, to simulate actions and understand potential credit consumption without committing.
- **Active Monitoring**: Keep a regular tab on your credit usage through the dashboard. This helps you avoid unexpected shortages and manage your budget better.

### Tracking Your Usage
Hover over the odometer icon in your navigation bar for a quick glance at your credits. Make sure you're looking at the right account context.
<img width="251" alt="Screenshot 2024-04-29 at 12 22 32 PM" src="https://github.com/duneanalytics/dune-docs/assets/168459178/c1956355-295d-45ac-971f-dca1e80c0b7c">
### Detailed Credit Information
Go to **Settings** → **Subscriptions** for a deeper dive into your credit usage and options.
### Handling Excess Usage
Exceeding your monthly allocation? Here's how to handle it:
1. Turn on the **pay-as-I-go** feature.
2. Set a cap in the **Limit extra credits** field to keep your spending in check.

## Pro Tips for Managing Credit Use
- **Plan Ahead:** Think through your data needs to consolidate queries, avoiding unnecessary executions.
- **Use Off-Peak Hours**: Data-heavy tasks can sometimes cost less when the system is quieter.
- **Regular Checks**: Monitor your credit meter like a hawk. Adapt your Dune activities to avoid running dry on credits.

**Comment by 0xBoxer** [comment]
closed with https://github.com/duneanalytics/dune-docs/pull/143

**Comment by 0xBoxer** [comment]
closed with closed with https://github.com/duneanalytics/dune-docs/pull/143
