### ISSUE TITLE
Executed query with decoded project give empty result

### ISSUE THREAD

**Issue by maygong** [duneanalytics/dune-docs#165]
Path: /web-app/query-editor/data-explorer
The smart contract that I decoded is [lunchbreaksmartcontlact]. When I perform basic queries on various tables in this dataset, it kept giving me the result 0, or N/A. I am certain the event counts in reality is NOT 0. What is going wrong here? 

<img width="1685" alt="Screenshot 2024-05-07 at 5 06 00 PM" src="https://github.com/duneanalytics/dune-docs/assets/29724319/8f7b53e5-d3d6-4386-a561-2c856be3f7eb">

**Comment by 0xBoxer** [comment]
Hey there, 

this issue is covered in our docs here:
https://docs.dune.com/data-catalog/evm/ethereum/decoded/call-tables#common-misconceptions

Please consult our Discord for operational questions like this in the future.

https://discord.gg/ErrzwBz
