### ISSUE TITLE
NO Embed button for me on Dune...

### ISSUE THREAD

**Issue by Spacewalker200** [duneanalytics/dune-docs#239]
Path: /web-app/embeds

Is probably a mistep on my part BUT simply trying to send a link in discord so that the graph appears in discord nicely. I can get a link which when clicked works, but not a preview to appear visually in the discord server, as the gif on their help page shows an example of (I have no 'embed' button appearing...) https://docs.dune.com/web-app/embeds#discord 

My screenshot shows the page i'm working from, no embed button, when i click share I get links that work but no preview like I said. 

<img width="1430" alt="Screenshot 2024-06-22 at 16 14 37" src="https://github.com/duneanalytics/dune-docs/assets/166240873/fdca7317-682b-4870-bfc6-45b10a80053e">

**Comment by 0xBoxer** [comment]
@Spacewalker200 the embed button is not part of the share dialouge that opens if you click share. (middle right in this screenshot) 

We need to update the screenshot, good catch!

**Comment by Spacewalker200** [comment]
Thanks, good answer!
